name: "Just echo a simple message"
description: "Runs dotnet tests with optional verbosity"

inputs:
  verbosity:
    description: "Verbosity level"
    required: false
    default: "normal"
  dotnet-version:
    description: "Version of .NET"
    required: true
    type: string
  project-location:
    description: "The test .csproj path"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: ./action.sh ${{ inputs.verbosity }} ${{ inputs.dotnet-version }} ${{ inputs.project-location }}
